// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_internal_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_internal_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_internal_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizationRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthorizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationResponse) Reset() {
	*x = AuthorizationResponse{}
	mi := &file_internal_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResponse) ProtoMessage() {}

func (x *AuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_internal_proto_server_proto protoreflect.FileDescriptor

const file_internal_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/server.proto\x12\n" +
	"gophkeeper\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\";\n" +
	"\x13RegistrationRequest\x12$\n" +
	"\x04User\x18\x01 \x01(\v2\x10.gophkeeper.UserR\x04User\",\n" +
	"\x14RegistrationResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"<\n" +
	"\x14AuthorizationRequest\x12$\n" +
	"\x04User\x18\x01 \x01(\v2\x10.gophkeeper.UserR\x04User\"-\n" +
	"\x15AuthorizationResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xa3\x01\n" +
	"\x04Auth\x12M\n" +
	"\bRegister\x12\x1f.gophkeeper.RegistrationRequest\x1a .gophkeeper.RegistrationResponse\x12L\n" +
	"\x05Login\x12 .gophkeeper.AuthorizationRequest\x1a!.gophkeeper.AuthorizationResponseB\x12Z\x10gophkeeper/protob\x06proto3"

var (
	file_internal_proto_server_proto_rawDescOnce sync.Once
	file_internal_proto_server_proto_rawDescData []byte
)

func file_internal_proto_server_proto_rawDescGZIP() []byte {
	file_internal_proto_server_proto_rawDescOnce.Do(func() {
		file_internal_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_server_proto_rawDesc), len(file_internal_proto_server_proto_rawDesc)))
	})
	return file_internal_proto_server_proto_rawDescData
}

var file_internal_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_server_proto_goTypes = []any{
	(*User)(nil),                  // 0: gophkeeper.User
	(*RegistrationRequest)(nil),   // 1: gophkeeper.RegistrationRequest
	(*RegistrationResponse)(nil),  // 2: gophkeeper.RegistrationResponse
	(*AuthorizationRequest)(nil),  // 3: gophkeeper.AuthorizationRequest
	(*AuthorizationResponse)(nil), // 4: gophkeeper.AuthorizationResponse
}
var file_internal_proto_server_proto_depIdxs = []int32{
	0, // 0: gophkeeper.RegistrationRequest.User:type_name -> gophkeeper.User
	0, // 1: gophkeeper.AuthorizationRequest.User:type_name -> gophkeeper.User
	1, // 2: gophkeeper.Auth.Register:input_type -> gophkeeper.RegistrationRequest
	3, // 3: gophkeeper.Auth.Login:input_type -> gophkeeper.AuthorizationRequest
	2, // 4: gophkeeper.Auth.Register:output_type -> gophkeeper.RegistrationResponse
	4, // 5: gophkeeper.Auth.Login:output_type -> gophkeeper.AuthorizationResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_server_proto_init() }
func file_internal_proto_server_proto_init() {
	if File_internal_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_server_proto_rawDesc), len(file_internal_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_server_proto_goTypes,
		DependencyIndexes: file_internal_proto_server_proto_depIdxs,
		MessageInfos:      file_internal_proto_server_proto_msgTypes,
	}.Build()
	File_internal_proto_server_proto = out.File
	file_internal_proto_server_proto_goTypes = nil
	file_internal_proto_server_proto_depIdxs = nil
}
